### PR TITLE
Changes to support signed authentication request for CIBA - https://g…

### PR DESCRIPTION
**Pull request by pritish-nitb**
…ithub.com/keycloak/kc-sig-fapi/issues/56

### CODE REVIEW

**Comment by pritish-nitb** [comment]
@tnorimat Could you please review this pull request. This is for signed authentication request support for CIBA

**Comment by tnorimat** [comment]
@pritish-nitb Hello. Thank you for your PR. I'll review it.

**Review by tnorimat — CHANGES_REQUESTED** [review]
LGTM. Could you write the arquillian integration test codes on `CIBATest`? To do so, it might be helpful to refer to `OIDCAdvancedRequestParamsTest` which is the test class for OIDC Request Object.

**Comment by tnorimat** [comment]
@pritish-nitb Thank you very much for your great work!
As usual, on behalf of you, I would like to send this PR to keycloak upstream with co-authored-by trailer showing your contribution as follows.
```
Co-authored-by: Pritish Joshi <pritish@banfico.com>
```
Is it OK?

**Comment by tnorimat** [comment]
@pritish-nitb I've sent PR incorporating your commits here to keycloak so that I will close this PR. Thank you.

**Pull request closed without merging**
