### PR TITLE
changed post request to decoupled auth server.

### PR DESCRIPTION
**Pull request by HryhoriiHevorkian**

### CODE REVIEW

**Comment by HryhoriiHevorkian** [comment]
Decoupled auth server PR: https://github.com/tnorimat/ciba-decoupled-authn-server/pull/2

**Review by tnorimat — COMMENTED** [review]
LGTM.

**Comment by HryhoriiHevorkian** [comment]
@tnorimat Could you please merge this PR if it is OK?

**Review by tnorimat — CHANGES_REQUESTED** [review]
@HryhoriiHevorkian I'm afraid `CIBATest` stalled. Could you please confirm that you could pass the PR merge criterion defined page 3 of [FAPI-CIBA Contribution Guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/FAPI-CIBA_ContributionGuide.pdf) ?

**Comment by HryhoriiHevorkian** [comment]
@tnorimat Yes, there was a mistake and now I have fixed it. Test passes with no errors now.

**Comment by tnorimat** [comment]
@HryhoriiHevorkian I'm afraid that your commits include the already merged PR (https://github.com/tnorimat/keycloak/pull/10). Could you rebase and make sure that your commits only include your codes?

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat , I have rebased my branch, currently it is up-to-date.

**Review by tnorimat — APPROVED** [review]

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Thank you very much!

**Pull request merged**
