### PR TITLE
Client Policy - Executor: Enforce secure signature algorithm for Signed JWT client authentication

### PR DESCRIPTION
**Pull request by andriimurashkin**
… Signed JWT client authentication

### CODE REVIEW

**Comment by andriimurashkin** [comment]
Hi @tnorimat 
Within this task do I need to validate JWT token header attribute "alg"?

**Comment by tnorimat** [comment]
@andriimurashkin Hello,

Considering the following scenario, it is preferable to check "alg" of JWT header.

- The client is registered with insecure signature algorithm setting for Signed JWT client authentication but is not applied to the policy including this executor.
- The client become applied to this policy after its registration.
- The client access to the token endpoint for requesting an access token and this policy is applied. If no check exists, this client can get the access token.

The secure signature algorithm are as follows.
- ES256
- ES384
- ES512
- PS256
- PS384
- PS512

The `ClientPolicyEvent`on which we need to check "alg" are as follows.
-    TOKEN_REQUEST
-    TOKEN_REFRESH
-    TOKEN_REVOKE
-    TOKEN_INTROSPECT
-    LOGOUT_REQUEST
namely, when the client is authenticated.

**Comment by andriimurashkin** [comment]
@tnorimat hello,

Could you help with:

* Am I right that conditions influence somehow on the flow of testing different events in enforcer? Which definite condition should I use for the proper event? 

* There is no way to get token model from executor context. I need this model to validate `alg` claim from it. How to obtain it?

Thanks in advance.

**Comment by tnorimat** [comment]
@andriimurashkin Hello.

I'll try to clarify your points as follows.

This executor needs to do the following works on each `ClientPolicyEvent`.
- check client settings and refuse them if needed
  - `REGISTER`
  - `UPDATE`
- check incoming requests and refuse them if needed
  - `TOKEN_REQUEST`
  - `TOKEN_REFRESH`
  - `TOKEN_REVOKE`
  - `TOKEN_INTROSPECT`
  - `LOGOUT_REQUEST`

### check/enforce client settings
You can check the signature algorithm for Signed JWT client authentication setting by using the following methods.

```
OIDCAdvancedConfigWrapper.fromClientRepresentation(ClientRepresentation rep).getTokenEndpointAuthSigningAlg()
```

On arquillian integration test, you can use the following condition to activate this executor.
```
        String policyName = "MyPolicy";
        createPolicy(policyName, DefaultClientPolicyProviderFactory.PROVIDER_ID, null, null, null);
        logger.info("... Created Policy : " + policyName);

        createCondition("ClientUpdateContextCondition", ClientUpdateContextConditionFactory.PROVIDER_ID, null, (ComponentRepresentation provider) -> {
            setConditionRegistrationMethods(provider, new ArrayList<>(Arrays.asList(
                    ClientUpdateContextConditionFactory.BY_AUTHENTICATED_USER,
                    ClientUpdateContextConditionFactory.BY_INITIAL_ACCESS_TOKEN,
                    ClientUpdateContextConditionFactory.BY_REGISTRATION_ACCESS_TOKEN)));
        });
        registerCondition("ClientUpdateContextCondition", policyName);
        logger.info("... Registered Condition : ClientUpdateContextConditionFactory");
```
 
### check incoming requests and refuse them if needed

To get "alg" from JWT's header,
```
        HttpRequest req = session.getContext().getContextObject(HttpRequest.class);
        String clientAssertion = req.getDecodedFormParameters().getFirst(OAuth2Constants.CLIENT_ASSERTION);
        JWSInput jws = new JWSInput(clientAssertion);
        String alg = jws.getHeader().getAlgorithm().name();
```
Every executor has KeycloakSession session as its member.

This specification of the error response needs to be the same as the current implementation for JWT authentication https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java

On arquillian integration test, you can use the following condition (Client Role) to activate this executor.
```
        // policy including client role condition
        String policyAlphaName = "MyPolicy-alpha";
        createPolicy(policyAlphaName, DefaultClientPolicyProviderFactory.PROVIDER_ID, null, null, null);
        logger.info("... Created Policy : " + policyAlphaName);

        createCondition(CLIENTROLES_CONDITION_ALPHA_NAME, ClientRolesConditionFactory.PROVIDER_ID, null, (ComponentRepresentation provider) -> {
            setConditionClientRoles(provider, new ArrayList<>(Arrays.asList("sample-client-role-alpha", "sample-client-role-zeta")));
        });
        registerCondition(CLIENTROLES_CONDITION_ALPHA_NAME, policyAlphaName);
        logger.info("... Registered Condition : " + CLIENTROLES_CONDITION_ALPHA_NAME);

        // crate a client with client role
        String clientAlphaId = "Alpha-App";
        String clientAlphaSecret = "secretAlpha";
        String cAlphaId = createClientByAdmin(clientAlphaId, (ClientRepresentation clientRep) -> {
            clientRep.setDefaultRoles((String[]) Arrays.asList("sample-client-role-alpha", "sample-client-role-common").toArray(new String[2]));
            clientRep.setSecret(clientAlphaSecret);
            clientRep.setClientAuthenticatorType(JWTClientSecretAuthenticator.PROVIDER_ID);
        });
```

**Comment by andriimurashkin** [comment]
Hi @tnorimat 
I'm a little confused, could you help me?

I've created `client_assertion` token using algorithm ES256:
```
private String createSignedRequestToken(String clientId, String realmInfoUrl, PrivateKey privateKey, PublicKey publicKey, String algorithm) throws NoSuchAlgorithmException, InvalidAlgorithmParameterException {
        KeyPairGenerator keyGen = KeyPairGenerator.getInstance("EC");
        SecureRandom randomGen = SecureRandom.getInstance("SHA1PRNG");
        ECGenParameterSpec ecSpec = new ECGenParameterSpec("secp256r1");
        keyGen.initialize(ecSpec, randomGen);
        KeyPair keyPair = keyGen.generateKeyPair();

        JsonWebToken jwt = createRequestToken(clientId, realmInfoUrl);
        String kid = KeyUtils.createKeyId(publicKey);
        SignatureSignerContext signer = oauth.createSigner(privateKey, kid, algorithm);
        return new JWSBuilder().kid(kid).jsonContent(jwt).sign(signer);
    }
```
 further in `JWTClientAuthenticator` I got an error due to public key is NULL:
```
           // Get client key and validate signature
            PublicKey clientPublicKey = getSignatureValidationKey(client, context, jws);
            if (clientPublicKey == null) {
                // Error response already set to context
                return;
            }
```

Where should I register my new keys to retrieve `clientPublicKey`?

Thanks in advance.

**Comment by tnorimat** [comment]
@andriimurashkin Hello.

As for registering EC key to keycloak, the current keycloak does not support such key registration.

Instead of it, keycloak supported the indirect way. 

- The client who want to use ES256 algorithm for JWT authentication (private_key_jwt), they need to provide the service which can provide keycloak with their EC key via their some dedicated endpoint.
- They also need to register this endpoint's url to keycloak as their client metadata "jwks_url".
- When verifying the JWT signed by this EC key, keycloak tries to get this key from the endpoint identified by "jwks_url".

It might be helpful to look at the following test method.
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java#L310
In this method, the EC key is registered to the server the test suite has prepared in advance. The corresponding code is as follows.
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java#L1194

**Comment by andriimurashkin** [comment]
@tnorimat thank you for explanation and examples.
Please review my pull request.

**Comment by tnorimat** [comment]
@andriimurashkin Thank you very much for your grate work!
By the way, you could directly send this PR to the keycloak upstream. Which do you like better,
 - You send this PR directly to keycloak upstream.
 - On behalf of you, I send this PR to keycloak upstream with `co-authored-by` trailer showing your contribution.

**Comment by andriimurashkin** [comment]
@tnorimat if you don't mind I select second option.
Thanks.

**Comment by tnorimat** [comment]
@andriimurashkin So, I will send this PR to keycloak upstream with `co-authored-by` trailer showing your contribution. Thank you!.

**Pull request merged**
