### PR TITLE
#78 Client Policy : Migrate Client Registration Policies (part1)

### PR DESCRIPTION
**Pull request by andriimurashkin**

### CODE REVIEW

**Comment by tnorimat** [comment]
@andriimurashkin On `ClientPolicyBasicsTest.testClientScopesClientRegistrationEnforcerExecutor`,
```
            //create client with allowed client scopes
            cAlphaId = createClientByAdmin("Alpha-clientScopes-App", (ClientRepresentation clientRep) -> {
                clientRep.setDefaultClientScopes(Collections.singletonList("foo"));
                clientRep.setOptionalClientScopes(Collections.singletonList("foo"));
            });
```
Client Scope needs to be registered to the realm in advance. If not, the client scope here specified has been ignored.
Therefore, if we run this test well, we need to register "foo" client scope to the realm "test" of the keycloak as both Default Client Scope and Optional Client Scope.

**Comment by andriimurashkin** [comment]
Hi @tnorimat, thanks for clarification.
I've fixed test that mentioned above. Do you mind if I join to  @HryhoriiHevorkian to help with migration of other client registration policies?

**Comment by tnorimat** [comment]
@andriimurashkin Hello.

Thank you for you fix. I will check it.

> Do you mind if I join to @HryhoriiHevorkian to help with migration of other client registration policies?

No, not at all.

**Review by tnorimat — APPROVED** [review]

**Comment by tnorimat** [comment]
@andriimurashkin LGTM for this PR. Before completing https://github.com/tnorimat/keycloak/pull/18 , we can migrate `MaxClientsClientRegistrationPolicy`. Which would you like better,

- implement `MaxClientsClientRegistrationPolicy` on this PR

- implement `MaxClientsClientRegistrationPolicy` on other PR

If you could choose the latter, I would like to merge this PR.

**Comment by andriimurashkin** [comment]
@tnorimat hello.

I have migrated `MaxClientsClientRegistrationEnforceExecutor` already in this PR.

> Implement the executor for the client registration policies ClientScopesClientRegistrationPolicy and MaxClientsClientRegistrationPolicy.

Done.

Or am I confusing something?

**Comment by tnorimat** [comment]
@andriimurashkin I'm sorry I've missed it. Thank you. I'll merge this PR.

**Comment by tnorimat** [comment]
@andriimurashkin Thank you!

**Pull request merged**
